version: '3.3'
services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        #image: mongo:4.4.29 # This is due to limitations in the Virtual Wall's hardware
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
          - /users/jrojasme/mongo-data:/data/db
        ports:
          - 27017:27017
        restart: always
        networks:
          - ldes
    generation-pipeline:
        container_name: generation-pipeline
        build: ./generation-pipeline
        ports:
          - 3333:3333
        volumes:
          - /users/jrojasme/rml-state:/opt/pipeline/state
        command: rdfc-pipeline.ttl
        networks:
          - ldes
        depends_on:
          - mongodb
    # ldes-server:
    #     build: ./ldes-server
    #     ports:
    #       - 3000:3000
    #     command: -b https://era.ilabt.imec.be
    #     networks:
    #       - ldes
    #     depends_on:
    #       - mongodb
    # consumption-pipeline:
    #     container_name: consumption-pipeline
    #     build: ./consumption-pipeline
    #     networks:
    #       - ldes
    #     depends_on:
    #       - ldes-server
    #       - virtuoso
    # virtuoso:
    #     container_name: virtuoso
    #     image: openlink/virtuoso-opensource-7:latest
    #     ports:
    #       - 1111:1111
    #       - 8890:8890
    #     restart: always
    #     networks:
    #       - ldes
networks:
    ldes:
      name: ldes-network